# Generated by Django 4.1.3 on 2023-02-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.CharField(default='', max_length=2000, verbose_name='description'),
            preserve_default=False,
        ),
    ]
