# Generated by Django 4.1.3 on 2023-02-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
